# Generated by Django 4.2.16 on 2024-10-21 17:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BotContent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('intro_circle_video', models.FileField(upload_to='bot_videos/', verbose_name='Intro Circle Video')),
                ('intro_text', models.TextField(verbose_name='Introductory Text')),
                ('intro_image', models.ImageField(upload_to='bot_images/', verbose_name='Instruction Image')),
                ('instruction_text', models.TextField(verbose_name='Instructions')),
                ('wild_inst_video', models.FileField(upload_to='bot_videos/', verbose_name='Wildberries Instruction Video')),
                ('ozon_inst_video', models.FileField(upload_to='bot_videos/', verbose_name='Ozon Instruction Video')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
            ],
            options={
                'verbose_name': 'Bot Content',
                'verbose_name_plural': 'Bot Content',
            },
        ),
        migrations.CreateModel(
            name='Prize',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name='Prize name')),
                ('description', models.CharField(blank=True, max_length=250, null=True, verbose_name='Prize description')),
                ('quantity', models.IntegerField(verbose_name='Playing quantity')),
                ('min_purchase', models.FloatField(blank=True, default=0, null=True, verbose_name='Min. Purchase Amt.')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
            ],
        ),
    ]
