# Generated by Django 4.2.16 on 2024-10-22 10:02

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0003_qrcheck_prize_available_winner'),
    ]

    operations = [
        migrations.AddField(
            model_name='qrcheck',
            name='created_at',
            field=models.DateTimeField(auto_created=True, default=django.utils.timezone.now, verbose_name='Created date'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='winner',
            name='created_at',
            field=models.DateTimeField(auto_created=True, default=django.utils.timezone.now, verbose_name='Created date'),
            preserve_default=False,
        ),
    ]
