# Generated by Django 4.2.16 on 2024-10-22 10:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0004_qrcheck_created_at_winner_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='qrcheck',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Created date'),
        ),
        migrations.AlterField(
            model_name='winner',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Created date'),
        ),
    ]
