# Generated by Django 4.2.16 on 2024-10-22 13:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0005_alter_qrcheck_created_at_alter_winner_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='botcontent',
            name='mega_prize_min',
            field=models.IntegerField(default=1000, verbose_name='Mega prize minimum amount'),
        ),
    ]
